version: 0.2

env:
  variables:
    S3_BUCKET: "mailshake-glue-scripts-dev"
    S3_PATH: "glue_jobs"
    # Format: glueJobName:scriptFile.py,glueJobName2:scriptFile2.py
    MAPPINGS: "Mailshake_ingestion_job:job_ingest.py,Mailshake_transformation_job:job_transform.py"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "===== INSTALL PHASE ====="
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
      - echo "Installing Python dependencies..."
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - python --version
      - pip --version

  pre_build:
    commands:
      - echo "===== PRE_BUILD PHASE ====="
      - echo "Current directory: $(pwd)"
      - echo "Listing files at repo root:"
      - ls -l
      - echo "Listing glue_jobs folder contents:"
      - ls -l glue_jobs/
      - echo "Validating Python scripts..."
      - python -m py_compile glue_jobs/*.py

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      - echo "Syncing Python scripts to S3..."
      - aws s3 sync glue_jobs/ s3://$S3_BUCKET/$S3_PATH/
      - echo "S3 sync completed. Listing bucket contents:"
      - aws s3 ls s3://$S3_BUCKET/$S3_PATH/

  post_build:
    commands:
      - echo "===== POST_BUILD PHASE ====="
      - echo "Debug: MAPPINGS variable = '$MAPPINGS'"
      - >
        IFS=',' read -ra pairs <<< "$MAPPINGS";
        for pair in "${pairs[@]}"; do
          job="${pair%%:*}";
          script="${pair##*:}";
          echo "Updating Glue Job: $job with script: $script";
          aws glue update-job \
            --job-name "$job" \
            --job-update "{\"Command\":{\"Name\":\"glueetl\",\"ScriptLocation\":\"s3://$S3_BUCKET/$S3_PATH/$script\",\"PythonVersion\":\"3\"}}";
        done
      - echo "All Glue jobs updated successfully."

# Artifacts not needed for Glue deployment
artifacts:
  files: []
