version: 0.2

env:
  variables:
    S3_BUCKET: "mailshake-glue-scripts-dev"
    S3_PATH: "glue_jobs"
    MAPPINGS: "Mailshake_ingestion_job:job_ingest.py,Mailshake_transformation_job:job_transform.py"

phases:
  install:
    commands:
      - echo "===== INSTALL PHASE ====="
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
      - echo "Installing Python dependencies (if requirements.txt exists)..."
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - echo "Python dependencies installed."

  pre_build:
    commands:
      - echo "===== PRE_BUILD PHASE ====="
      - echo "Current working directory: $(pwd)"
      - echo "Listing all files at repo root:"
      - ls -l
      - echo "Listing glue_jobs folder contents:"
      - ls -l glue_jobs/
      - python -m py_compile glue_jobs/*.py

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      - echo "Syncing glue_jobs/ to S3..."
      - if [ -d glue_jobs ]; then aws s3 sync glue_jobs/ s3://$S3_BUCKET/$S3_PATH/; else echo "Skipping S3 sync, glue_jobs folder not found."; fi
      - echo "S3 sync completed."
      - echo "Verifying files in S3 bucket:"
      - aws s3 ls s3://$S3_BUCKET/$S3_PATH/

  post_build:
    commands:
      - echo "===== POST_BUILD PHASE ====="
      - echo "Debug: MAPPINGS variable = '$MAPPINGS'"
      - echo "Updating Glue jobs..."
      - |
        IFS=',' read -ra pairs <<< "$MAPPINGS"
        for pair in "${pairs[@]}"; do
          job="${pair%%:*}"
          script="${pair##*:}"
          echo "Updating Glue Job: $job with script: $script"
          aws glue update-job \
            --job-name "$job" \
            --job-update "{\"Command\":{\"Name\":\"glueetl\",\"ScriptLocation\":\"s3://$S3_BUCKET/$S3_PATH/$script\",\"PythonVersion\":\"3\"}}"
        done
      - echo "All Glue jobs updated successfully."

artifacts:
  files: []
